name: Run All Tests and Merge Reports
env:
  WORKFLOW_TOKEN: ${{ secrets.TOKEN }}

on:
  workflow_dispatch:   # manual trigger

jobs:
  trigger-repo-a:
    name: Trigger Repo A Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check if secret exists
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Actor: $GITHUB_ACTOR"
          echo "Run Id: $GITHUB_RUN_ID"
          echo "Run Number: $GUTHUB_RUN_NUMBER"
      - name: Trigger Repo A Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $WORKFLOW_TOKEN" \
            https://api.github.com/repos/rajasekharyerva/sample-workflow/actions/workflows/test.yml/dispatches \
            -d '{"ref":"main"}'


  trigger-repo-b:
    name: Trigger Repo B Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check if secret exists
        run: |
          if [ -z "${{ secrets.TOKEN }}" ]; then
            echo "Secret is empty or not set!"
          else
            echo "Secret is set (masked for security)"
          fi
      - name: Trigger Repo B Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.TOKEN }}" \
            https://api.github.com/repos/rajasekharyerva/sample-workflow-2/actions/workflows/test.yml/dispatches \
            -d '{\"ref\":\"main\"}'
  

  merge-reports:
    name: Merge Reports
    needs:
      - trigger-repo-a
      - trigger-repo-b
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout aggregator repo
      - uses: actions/checkout@v4

      # 2. Download artifacts from Repo A workflow
      - name: Download Repo A Report
        uses: actions/download-artifact@v4
        with:
          name: repo-a-report
          path: reports/repo-a

      # 3. Download artifacts from Repo B workflow
      - name: Download Repo B Report
        uses: actions/download-artifact@v4
        with:
          name: repo-b-report
          path: reports/repo-b

      # 4. Merge JSON reports
      - name: Merge JSON Reports
        run: |
          mkdir -p target/merged-reports
          cp reports/repo-a/*.json target/merged-reports/ || echo "No reports from A"
          cp reports/repo-b/*.json target/merged-reports/ || echo "No reports from B"
          echo "Reports copied to target/merged-reports"

      # 5. Generate consolidated HTML report using Maven plugin
      - name: Generate HTML Report
        run: mvn verify -DskipTests=true

      # 6. Upload merged report as artifact
      - name: Upload Merged Report
        uses: actions/upload-artifact@v4
        with:
          name: merged-cucumber-report
          path: target/generated-report/
